### ISSUE TITLE
re-enable edit in UI when it works again

### ISSUE THREAD

**Issue by zippy** [holochain/clutter#11]
we hid the edit link because it wasn't working

**Comment by celestialhanley** [comment]
when clicking on "settings" to change handle name, a new user is created and all meows and people followed disappears. basicially reseting to brand new user. desired behavior: when changing handle, it's simply a name change and all feed activity remains.

**Comment by celestialhanley** [comment]
edit previous comment: implement "name" and "handle" where name is changeable and handle is NOT.
