### ISSUE TITLE
minor bugs in clutter

### ISSUE THREAD

**Issue by matthewjosef** [holochain/clutter#12]
- [ ] Can’t follow a user if they are not currently online.
- [x] No way to discover new users within the app (do both of these require indexing? Or a list of handles to be maintained somewhere?)
- [x] Unfollow doesn’t seem to be working
- [x] I might be wrong, but I thought I had noticed that when a user goes offline, their meows disappear from my feed (or at least don't populate the next time I come online)
- [x] Clicking a handle doesn’t seem to filter posts

**Comment by rayzer42** [comment]
Perhaps these things are best left to be handled in the refactor I am about to embark on. @zippy @lucksus what say you?

**Comment by zippy** [comment]
creating new ticket for follow issue,  everything else complete
