### ISSUE TITLE
feature: implement favorites on each post

### ISSUE THREAD

**Issue by tishakitkat** [holochain/clutter#2]
Implementing favorites where the posts liked by the author gets commited to the author's source chain

**Comment by tishakitkat** [comment]
Implementing favorites where the posts liked by the author gets commited to the author's source chain

**Comment by celestialhanley** [comment]
like in Twitter, add a "heart" or "like" feature in each post. when you click the heart, it turns red. when you click a heart that's red, it no longer displays as red.

**Comment by science-girl** [comment]
As a user I would like to see an integer representing the number of other users who have liked a post next to the heart icon (which is unfilled if I have not liked it).  As a user, I would like to mark posts I like with a red heart icon and see the count next to the heart icon increment by 1.
