### ISSUE TITLE
Running "yarn build" from Docker instructions fails because no package.json

### ISSUE THREAD

**Issue by shawnlauzon** [Holochain/clutter#37]
Running the `yarn build` command from the clutter directory fails because there is no `package.json` file there.

![image](https://user-images.githubusercontent.com/611529/35413762-7718b720-01ee-11e8-8554-2a341f8401fc.png)

However if I skip the command, everything works ok. So I don't think this command is necessary for the Docker instructions.

**Comment by Connoropolous** [comment]
ah, this points out a flaw in the documentation...
you need to be in the `ui-src` directory when you run `yarn install` and `yarn build`

I will look at addressing that

**Comment by Connoropolous** [comment]
fixed this now in https://github.com/Holochain/clutter/commit/04cc80b54823c6c189af146346cd4f5f45f279e0

**Comment by Connoropolous** [comment]
@shawnlauzon let me know if it helps

**Comment by shawnlauzon** [comment]
Ahh, maybe that's why the docker command worked for me: because I had
already figured that out :)

Yep, thanks for that, works for me now!
