### ISSUE TITLE
Tests fail `TypeError: Cannot access member 'length' of undefined`

### ISSUE THREAD

**Issue by shawnlauzon** [Holochain/clutter#38]
Running `hcdev test`, multiple tests fail with the same error:

![image](https://user-images.githubusercontent.com/611529/35414776-86ff7770-01f1-11e8-9aaf-1884c3a13f8e.png)

Might there be a dependency on a specific version of Holochain?

**Comment by Connoropolous** [comment]
@shawnlauzon sorry, some code that was not supposed to be merged was, and that is the problem. I am going to push a fix now

**Comment by shawnlauzon** [comment]
Tests run clean now 👍

**Comment by philipbeadle** [comment]
You can see the build results here Shawn https://travis-ci.org/Holochain/clutter/builds/333926638
