### ISSUE TITLE
feature: profile picture

### ISSUE THREAD

**Issue by artbrock** [holochain/clutter#42]
As a clutter user I want to be able to upload my own profile picture and see the profile pictures of others.

(Click on left hand cat with bird in mouth... to change your profile picture.)

Resizing and everyting done client-side, MVP.

This will mean dealing with the question of file storage of pictures... I propose Base64 encoding with size limit (5 Mb?) and put it into a Holochain entry.

**Comment by thedavidmeister** [comment]
MVP scope for this ticket:

- HTML upload button
- no drag and drop or anything
- no cropping etc.
- all image processing happens client side
- can limit to one file type (e.g. jpg or png)
- client takes file, base64 encodes it and ships straight to DHT

@philipbeadle has done something similar in the past
