### ISSUE TITLE
cat eating bird image breaks when on path

### ISSUE THREAD

**Issue by thedavidmeister** [Holochain/clutter#50]
<img width="190" alt="screen shot 2018-03-06 at 11 20 33 am" src="https://user-images.githubusercontent.com/629710/37007231-6733994a-2130-11e8-91b5-65e8d7753876.png">

path should have a leading `/` to prevent it breaking on urls like `http://localhost:5141/u/QmWQVaqEayZJWnvxLtsKr1iyeTDp3s7m7TTE36HhAUTiTK`

**Comment by philipbeadle** [comment]
Done.
