### ISSUE TITLE
travis should be running `hcdev test`

### ISSUE THREAD

**Issue by thedavidmeister** [Holochain/clutter#52]

**Comment by thedavidmeister** [comment]
i played around with various permutations of the instructions for installing hcdev with go in travis

the summary results:

- installing go with `apt-get install golang-go` installs a version that is too all https://travis-ci.org/Holochain/clutter/builds/349602730?utm_source=github_status&utm_medium=notification
- installing a newer version fails to find go command https://travis-ci.org/Holochain/clutter/builds/349635716?utm_source=github_status&utm_medium=notification

This is running against a node Travis box (elsewhere that these tests worked was apparently using a prebuilt go Travis build)

There's also the concern that setting up go from scratch every time will be very slow for testing

Conclusion is that we should try to use docker instead

**Comment by thedavidmeister** [comment]
Also, this is potentially worth considering - https://circleci.com/

Circle is basically Travis but with some neat extra functionality - like being able to ssh into a build for debugging (rather than changing one tiny thing and waiting for a whole build to see if it worked)

**Comment by philipbeadle** [comment]
Done, you can see the results here. https://travis-ci.org/Holochain/clutter/builds/354137137
