### ISSUE TITLE
client side error on getfollow

### ISSUE THREAD

**Issue by joshuavial** [holochain/clutter#64]
I'm running node 8.9.4, npm 5.6.0 on mac OS 10.12.6. Checking out master and running yarn install and yarn build in ui-src seems to work fine.

then I run `hcadmin join . clutter` and `hcd clutter` which shows me a DNA hash of `QmUSHVAekeYGHoayHTbzwpRd8hR1gunpT4SRJGa4NaFRT2` and I can see my IP address listed in http://bootstrap.holochain.net:10000/QmUSHVAekeYGHoayHTbzwpRd8hR1gunpT4SRJGa4NaFRT2

When I start interacting with the app though I see client side errors in both Chrome and Firefox. I can set my handle ok and see the results reflected on the bootstrap server but the getFollow api call gives

```
{errorMessage: "uvarint: buffer too small", function: "getLinks", name: "HolochainError",…}
errorMessage
:
"uvarint: buffer too small"
function
:
"getLinks"
name
:
"HolochainError"
source
:
{column: "17", functionName: "doGetLink", line: "265"}
```

and when I go to the follow page it shows a blank screen and an error message in the browser console of 
```
Follow.js:18 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at Follow.js:18
    at Array.filter (<anonymous>)
    at e.value (Follow.js:17)
    at c (react-dom.production.min.js:130)
    at beginWork (react-dom.production.min.js:133)
    at o (react-dom.production.min.js:161)
    at a (react-dom.production.min.js:161)
    at u (react-dom.production.min.js:162)
    at _ (react-dom.production.min.js:169)
    at w (react-dom.production.min.js:168)
```

**Comment by Connoropolous** [comment]
@joshuavial aha, the issue may have arisen because you are likely on the latest 'develop' branch of holochain, but `master` on clutter may correspond to `master` on holochain. If you checkout the develop branch of clutter instead, it will likely work

**Comment by lucksus** [comment]
@joshuavial, did switching to develop as @Connoropolous suggested solve this issue for you?
