### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by Sixzero** [holochain/clutter#66]
I installed everything and tested how things work.
For 2 hours I let things run in the background, then suddenly the memory usage of 'hcdev' increased to 14GB for each of the two 'clutter' processes and my 32 GB memory of my computer just got filled and it crashed. 
What causes it?

**Comment by lucksus** [comment]
I believe this was an old version. I can‘t see this problem anymore with the current Holochain code. @Sixzero, can you confirm?
