### ISSUE TITLE
update hcdev flags (remove --no-nat-upnp)

### ISSUE THREAD

**Issue by philipbeadle** [holochain/clutter#67]
New version of hc has different flags. Update docker-compose and travis.

**Comment by clarenceb** [comment]
The `docker-compose,yml` file needs updating to remove the `-no-nat-upnp` flag and change `-port=XXXX` to `-DHTport=XXXX` for the `hcdev` command-line usage.  This also needs to be done in the `.travis.yml` file.

**Comment by philipbeadle** [comment]
All done.
