### ISSUE TITLE
meow links should be clickable 

### ISSUE THREAD

**Issue by celestialhanley** [holochain/clutter#69]
when a user posts a meow with a link, it is not currently clickable. desired behavior: clicking link will open it in new tab. 

As an alpha 1 user I want to have links clickable if the link is in the proper and full format with "https://" in front.

**Comment by zippy** [comment]
it may be a good idea to coordinate with @philipbeadle to create a UI test that reveals this problem, so that when it gets fixed, it doesn' break again later.

**Comment by lucksus** [comment]
RegExp for urls: https://stackoverflow.com/questions/3809401/what-is-a-good-regular-expression-to-match-a-url

**Comment by science-girl** [comment]
https://stackoverflow.com/questions/37684/how-to-replace-plain-urls-with-links
