### ISSUE TITLE
ui: set handle modal box

### ISSUE THREAD

**Issue by science-girl** [holochain/clutter#73]
The first time a user opens clutter, a modal box appears. User must set handle to continue.

**Comment by lucksus** [comment]
what is this ticket about? what is the bug?

**Comment by science-girl** [comment]
Users can't re-use their handle - if I set my handle to 'lindsey' and
then change my handle to 'nico', I can't use 'lindsey' again.  Also,
users can not set their handle or set their handle to the empty string
and still use the app.  We decided to make the handle set once with a
modal upon the first time they use the app (and not re-set that), but
also they can re-set their name, which is how twitter works.
