### ISSUE TITLE
Document why: Seeing/following users that are not online

### ISSUE THREAD

**Issue by lucksus** [holochain/clutter#74]
As a Clutter user I want to be able to follow somebody (and see their meows) who was online before but is not online now so I can actually use Clutter as a replacement for Twitter.

**Comment by celestialhanley** [comment]
From my perspective yes, we would want to be able to follow offline users and see their recent activity, the same way Twitter functions.

**Comment by zippy** [comment]
There may just be some timing issues where it takes a while for things to synchronize. Eg. today I came back to the UI and it started show luksus.

**Comment by lucksus** [comment]
I am just playing around with the current clutter develop (Qmbtpaf8GJCKi1MxCN4ynXQjKXsQwppYfGKL8s9bs7sT2t) that we started last night on several machines including the HoloPorts. I've spawn two test nodes with ```hcdev web```, one while my hcd based node was running, and then one without it running. 

* The first instance ```nicos-test-1``` could see ```lucksus``` which was running when it came up
* The second one ```nicos-test-2``` did not see ```lucksus``` which I had shut down before booting ```nicos-test-2``` (but holoport should have connected both)
* I then started the ```lucksus``` while ```nicos-test-2``` was online:
   * ```nicos-test-2``` now started seeing ```lucksus```
  * **BUT**: ```nicos-test-2``` did not start seeing ```nicos-test-1```, which ```lucksus``` is seeing.
**=>** I interpret this as a quite strong indication for gossip being broken. ```nicos-test-2``` starting to see ```lucksus``` after booting the ```lucksus``` node almost certainly comes from gossip between ```lucksus``` and ```nicos-test-2```. It should have gotten the gossip from ```holoport_plus``` but ok. But then not getting the information about ```nicos-test-1``` through this gossip is maybe the same problem that prevented ```holoport_plus``` from gossiping about ```lucksus```

@zippy ?

**Comment by lucksus** [comment]
I also looked into the code that handles handles ;) in clutter and compared the debug output it creates. This looks reasonable and not too complex. Basically the handles just hang on ```App.DNA.hash``` as ```directory``` and getHandles() just gets all of those links which are exactly the same thing we see in the UI.

**=>** I don't see a problem with Clutter, rather HC and gossip

**Comment by lucksus** [comment]
@zippy and I had several more discussions. Main take away: this is **not a bug** but expected behavior with the current incomplete feature set of Holochain. (To be more precise: a result of the combination of *source validation* and *100% redundancy factor*)

Explanation:
* In Clutter, user handles are being stored as links on App.DNA.Hash
* Every node as at least one link entry for App.DNA.Hash: itself (since with 100% redundancy, every node is responsible for storing everything)
* This has the consequence that a getLinks() call to retrieve handles always resolves locally, without triggering a DHT lookup
* Through DHT gossip, we receive new entries from the DHT but since our nodes feels responsible (100% redundancy) it wants to validate the entry first by talking to the source before treating the entry as valid/existant
* If the source has no (not yet) online overlap time with our node, the new handle link entry can't be validated and is not shown

**Comment by lucksus** [comment]
We should document this fact in the HC documentation

**Comment by zippy** [comment]
@lucksus @thedavidmeister I've added [an article](https://developer.holochain.org/Validating_DHT_Issues)  does this seem like enough for this ticket, or should we go deeper?

**Comment by lucksus** [comment]
Yeah, I think so, @zippy. But I've spotted some typos. I've just signed up and believe I need to be approved to make changes, right?

**Comment by zippy** [comment]
I approved your account.

**Comment by thedavidmeister** [comment]
@zippy looks ok, but i wonder, why can't i do validation with the data alone? why must i talk to the source to perform validation?

**Comment by thedavidmeister** [comment]
@zippy mmm i think there's a difference between proxy validation (sounds like "light wallet" to me) and wanting to be able to validate data independant of the source (wanting to do "offline" validation of data)
