### ISSUE TITLE
Part of the dev team

### ISSUE THREAD

**Issue by Catley94** [holochain/clutter#78]
This isn't a problem, it's a request, I would like to become part of dev team as I have a change I would like to commit/push but it's failing authentication on github desktop.

The file change I have requested is:

Clutter > test > posts.json

But I can't find any instructions on how to make sure that my commits are being pushed through and checked.

**Comment by zippy** [comment]
Hey there, thanks for your fixes.  For now the best way to do this is simply to do the usual thing of forking the repo, pushing your change to your own repo and creating a pull request.  We are happy to merge in contributor changes that way.  

Thanks!
